# Change these first
owner: amagno-io # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Amagno Business Cloud
    url: https://amagno.cloud/amagnoservice/amagnoservice.svc
    icon: https://amagno.de/wp-content/uploads/2018/02/favicon-2.ico
  - name: Amagno API
    url: https://amagno.me/api/v2
    icon: https://amagno.de/wp-content/uploads/2018/02/favicon-2.ico
  - name: amagno.de
    url: https://amagno.de
    icon: https://amagno.de/wp-content/uploads/2018/02/favicon-2.ico
  - name: amagno.ch
    url: https://amagno.ch
    icon: https://amagno.de/wp-content/uploads/2018/02/favicon-2.ico
  - name: amagno.co.uk
    url: https://amagno.co.uk
    icon: https://amagno.de/wp-content/uploads/2018/02/favicon-2.ico

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.amagno.cloud
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://amagno.de/wp-content/uploads/2018/02/amagno-ecm-logo-header.png
  name: Business Cloud - Status
  introTitle: "**Amagno Business Cloud** open-source uptime monitor and status page, powered by upptime & GitHub."
  introMessage: This is a status page which uses **real-time** data from our infrastructure.
  navbar:
    - title: Status
      href: /
    - title: Service Desk
      href: https://amagno.atlassian.net/servicedesk/customer/portal/6

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
